# Generated by Django 3.0.3 on 2020-03-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_auto_20200311_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='one_task',
            name='big_subject',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], max_length=50),
        ),
    ]
