# Generated by Django 3.0.3 on 2020-03-12 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_auto_20200311_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('progress', models.CharField(max_length=50)),
                ('start_time', models.DateField(blank=True, max_length=50)),
                ('end_time', models.DateField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Big_subject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('big_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.Big_subject')),
            ],
        ),
        migrations.DeleteModel(
            name='One_task',
        ),
        migrations.AddField(
            model_name='activity',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.Task'),
        ),
    ]
