# Generated by Django 3.0.3 on 2020-03-12 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_auto_20200312_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='big_subject',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='task',
            name='big_subject',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.Big_subject'),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
