# Generated by Django 3.0.3 on 2020-03-14 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0012_auto_20200314_0513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='my_app.Task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='big_subject',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='my_app.Big_subject'),
        ),
    ]
